// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: VulcanTransferProto.proto

package org.huangyr.project.vulcan.runner.server.proto;

public final class VulcanTransferProto {
  private VulcanTransferProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_huangyr_project_vulcan_proto_VulcanHeartPackage_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_org_huangyr_project_vulcan_proto_VulcanHeartPackage_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_huangyr_project_vulcan_proto_ServerCommandPackage_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_org_huangyr_project_vulcan_proto_ServerCommandPackage_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_huangyr_project_vulcan_proto_RunnerNodeInfo_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_org_huangyr_project_vulcan_proto_RunnerNodeInfo_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\031VulcanTransferProto.proto\022 org.huangyr" +
      ".project.vulcan.proto\"\216\001\n\022VulcanHeartPac" +
      "kage\022\017\n\007message\030\001 \001(\t\022\n\n\002ip\030\002 \001(\t\022\021\n\thea" +
      "rtTime\030\003 \001(\004\022H\n\016runnerNodeInfo\030\004 \001(\01320.o" +
      "rg.huangyr.project.vulcan.proto.RunnerNo" +
      "deInfo\"\222\001\n\024ServerCommandPackage\022\022\n\nresul" +
      "tCode\030\001 \001(\005\022:\n\007command\030\002 \001(\0162).org.huang" +
      "yr.project.vulcan.proto.Command\022\017\n\007messa" +
      "ge\030\003 \001(\t\022\031\n\021responseHeartTime\030\004 \001(\004\"\020\n\016R" +
      "unnerNodeInfo*0\n\007Command\022\n\n\006NORMAL\020\000\022\014\n\010" +
      "SHUTDOWN\020\001\022\013\n\007UPGRADE\020\002B9\n org.huangyr.p" +
      "roject.vulcan.protoB\023VulcanTransferProto" +
      "P\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_org_huangyr_project_vulcan_proto_VulcanHeartPackage_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_org_huangyr_project_vulcan_proto_VulcanHeartPackage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_org_huangyr_project_vulcan_proto_VulcanHeartPackage_descriptor,
        new java.lang.String[] { "Message", "Ip", "HeartTime", "RunnerNodeInfo", });
    internal_static_org_huangyr_project_vulcan_proto_ServerCommandPackage_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_org_huangyr_project_vulcan_proto_ServerCommandPackage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_org_huangyr_project_vulcan_proto_ServerCommandPackage_descriptor,
        new java.lang.String[] { "ResultCode", "Command", "Message", "ResponseHeartTime", });
    internal_static_org_huangyr_project_vulcan_proto_RunnerNodeInfo_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_org_huangyr_project_vulcan_proto_RunnerNodeInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_org_huangyr_project_vulcan_proto_RunnerNodeInfo_descriptor,
        new java.lang.String[] { });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
