// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: VulcanTransferProto.proto

package org.huangyr.project.vulcan.proto;

public interface HeartResultPackageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:cn.com.essence.proto.HeartResultPackage)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * 心跳响应结果
   * </pre>
   *
   * <code>int32 resultCode = 1;</code>
   */
  int getResultCode();

  /**
   * <pre>
   * 心跳结果消息
   * </pre>
   *
   * <code>string message = 2;</code>
   */
  java.lang.String getMessage();
  /**
   * <pre>
   * 心跳结果消息
   * </pre>
   *
   * <code>string message = 2;</code>
   */
  com.google.protobuf.ByteString
      getMessageBytes();

  /**
   * <pre>
   * 响应命令
   * </pre>
   *
   * <code>.cn.com.essence.proto.Command command = 3;</code>
   */
  int getCommandValue();
  /**
   * <pre>
   * 响应命令
   * </pre>
   *
   * <code>.cn.com.essence.proto.Command command = 3;</code>
   */
  org.huangyr.project.vulcan.proto.Command getCommand();

  /**
   * <pre>
   * 发送心跳时间
   * </pre>
   *
   * <code>uint64 sendHeartTime = 4;</code>
   */
  long getSendHeartTime();

  /**
   * <pre>
   * 收到心跳时间
   * </pre>
   *
   * <code>uint64 receiveHeartTime = 5;</code>
   */
  long getReceiveHeartTime();

  /**
   * <pre>
   * 心跳响应时间
   * </pre>
   *
   * <code>uint64 responseHeartTime = 6;</code>
   */
  long getResponseHeartTime();
}
