// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: VulcanTransferProto.proto

package org.huangyr.project.vulcan.proto;

public interface RunnerNodeInfoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:org.huangyr.project.vulcan.proto.RunnerNodeInfo)
    com.google.protobuf.MessageOrBuilder {
}
