// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: VulcanTransferProto.proto

package org.huangyr.project.vulcan.proto;

public interface ServerCommandPackageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:org.huangyr.project.vulcan.proto.ServerCommandPackage)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * 响应结果 / 消息标识
   * </pre>
   *
   * <code>int32 resultCode = 1;</code>
   */
  int getResultCode();

  /**
   * <pre>
   * Server指令
   * </pre>
   *
   * <code>.org.huangyr.project.vulcan.proto.Command command = 2;</code>
   */
  int getCommandValue();
  /**
   * <pre>
   * Server指令
   * </pre>
   *
   * <code>.org.huangyr.project.vulcan.proto.Command command = 2;</code>
   */
  org.huangyr.project.vulcan.proto.Command getCommand();

  /**
   * <pre>
   * Server指令详情
   * </pre>
   *
   * <code>string message = 3;</code>
   */
  java.lang.String getMessage();
  /**
   * <pre>
   * Server指令详情
   * </pre>
   *
   * <code>string message = 3;</code>
   */
  com.google.protobuf.ByteString
      getMessageBytes();

  /**
   * <pre>
   * 消息发送时间
   * </pre>
   *
   * <code>uint64 responseHeartTime = 4;</code>
   */
  long getResponseHeartTime();
}
