// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: VulcanTransferProto.proto

package org.huangyr.project.vulcan.proto;

public interface VulcanHeartPackageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:org.huangyr.project.vulcan.proto.VulcanHeartPackage)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * 心跳消息
   * </pre>
   *
   * <code>string message = 1;</code>
   */
  java.lang.String getMessage();
  /**
   * <pre>
   * 心跳消息
   * </pre>
   *
   * <code>string message = 1;</code>
   */
  com.google.protobuf.ByteString
      getMessageBytes();

  /**
   * <pre>
   * 发送心跳的机器IP
   * </pre>
   *
   * <code>string ip = 2;</code>
   */
  java.lang.String getIp();
  /**
   * <pre>
   * 发送心跳的机器IP
   * </pre>
   *
   * <code>string ip = 2;</code>
   */
  com.google.protobuf.ByteString
      getIpBytes();

  /**
   * <pre>
   * 发送心跳时间
   * </pre>
   *
   * <code>uint64 heartTime = 3;</code>
   */
  long getHeartTime();
}
