// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: VulcanTransferProto.proto

package org.huangyr.project.vulcan.proto;

public final class VulcanTransferProto {
  private VulcanTransferProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_huangyr_project_vulcan_proto_VulcanHeartPackage_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_org_huangyr_project_vulcan_proto_VulcanHeartPackage_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_huangyr_project_vulcan_proto_ServerCommandPackage_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_org_huangyr_project_vulcan_proto_ServerCommandPackage_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_huangyr_project_vulcan_proto_RunnerNodeInfo_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_org_huangyr_project_vulcan_proto_RunnerNodeInfo_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\031VulcanTransferProto.proto\022 org.huangyr" +
      ".project.vulcan.proto\"\240\001\n\022VulcanHeartPac" +
      "kage\022\017\n\007message\030\001 \001(\t\022\020\n\010nodename\030\002 \001(\t\022" +
      "\n\n\002ip\030\003 \001(\t\022\021\n\theartTime\030\004 \001(\004\022H\n\016runner" +
      "NodeInfo\030\005 \001(\01320.org.huangyr.project.vul" +
      "can.proto.RunnerNodeInfo\"\222\001\n\024ServerComma" +
      "ndPackage\022\022\n\nresultCode\030\001 \001(\005\022:\n\007command" +
      "\030\002 \001(\0162).org.huangyr.project.vulcan.prot" +
      "o.Command\022\017\n\007message\030\003 \001(\t\022\031\n\021responseHe" +
      "artTime\030\004 \001(\004\"\020\n\016RunnerNodeInfo*0\n\007Comma" +
      "nd\022\n\n\006NORMAL\020\000\022\014\n\010SHUTDOWN\020\001\022\013\n\007UPGRADE\020" +
      "\002B9\n org.huangyr.project.vulcan.protoB\023V" +
      "ulcanTransferProtoP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_org_huangyr_project_vulcan_proto_VulcanHeartPackage_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_org_huangyr_project_vulcan_proto_VulcanHeartPackage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_org_huangyr_project_vulcan_proto_VulcanHeartPackage_descriptor,
        new java.lang.String[] { "Message", "Nodename", "Ip", "HeartTime", "RunnerNodeInfo", });
    internal_static_org_huangyr_project_vulcan_proto_ServerCommandPackage_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_org_huangyr_project_vulcan_proto_ServerCommandPackage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_org_huangyr_project_vulcan_proto_ServerCommandPackage_descriptor,
        new java.lang.String[] { "ResultCode", "Command", "Message", "ResponseHeartTime", });
    internal_static_org_huangyr_project_vulcan_proto_RunnerNodeInfo_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_org_huangyr_project_vulcan_proto_RunnerNodeInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_org_huangyr_project_vulcan_proto_RunnerNodeInfo_descriptor,
        new java.lang.String[] { });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
