// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: VulcanTransferProto.proto

package org.huangyr.project.vulcan.proto;

public interface VulcanHeartPackageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:org.huangyr.project.vulcan.proto.VulcanHeartPackage)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * 心跳消息
   * </pre>
   *
   * <code>string message = 1;</code>
   */
  java.lang.String getMessage();
  /**
   * <pre>
   * 心跳消息
   * </pre>
   *
   * <code>string message = 1;</code>
   */
  com.google.protobuf.ByteString
      getMessageBytes();

  /**
   * <pre>
   * 机器的名称
   * </pre>
   *
   * <code>string nodename = 2;</code>
   */
  java.lang.String getNodename();
  /**
   * <pre>
   * 机器的名称
   * </pre>
   *
   * <code>string nodename = 2;</code>
   */
  com.google.protobuf.ByteString
      getNodenameBytes();

  /**
   * <pre>
   * 发送心跳的机器IP
   * </pre>
   *
   * <code>string ip = 3;</code>
   */
  java.lang.String getIp();
  /**
   * <pre>
   * 发送心跳的机器IP
   * </pre>
   *
   * <code>string ip = 3;</code>
   */
  com.google.protobuf.ByteString
      getIpBytes();

  /**
   * <pre>
   * 发送心跳时间
   * </pre>
   *
   * <code>uint64 heartTime = 4;</code>
   */
  long getHeartTime();

  /**
   * <pre>
   * 上报Runner自身节点信息
   * </pre>
   *
   * <code>.org.huangyr.project.vulcan.proto.RunnerNodeInfo runnerNodeInfo = 5;</code>
   */
  boolean hasRunnerNodeInfo();
  /**
   * <pre>
   * 上报Runner自身节点信息
   * </pre>
   *
   * <code>.org.huangyr.project.vulcan.proto.RunnerNodeInfo runnerNodeInfo = 5;</code>
   */
  org.huangyr.project.vulcan.proto.RunnerNodeInfo getRunnerNodeInfo();
  /**
   * <pre>
   * 上报Runner自身节点信息
   * </pre>
   *
   * <code>.org.huangyr.project.vulcan.proto.RunnerNodeInfo runnerNodeInfo = 5;</code>
   */
  org.huangyr.project.vulcan.proto.RunnerNodeInfoOrBuilder getRunnerNodeInfoOrBuilder();
}
